[package]
name = "filecabinet"
version = "0.1.0"
authors = ["Danielle Jenkins <git@d6e.io>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "2.33.2"
rocket = "0.4.5"
chacha20poly1305 = "0.5.1"
rand = "0.7.3"
blake3 = "0.3.6"

